config/routes.rb
Rails.application.routes.draw do

  # get 'products/index'
  # get 'products/show'

  get 'products', to: 'products#index', as: 'products'
# ^verb  ^URI          ^controller#action    ^ refer: products_path

  get 'products/:id', to: 'products#show',  as: 'product' , id: /\d+/
  # ^verb  ^URI          ^controller  ^action    ^ refer: product_path  ^constraint (for numeric values only)

  get 'about' => 'products#about'

  get 'blog', to: redirect('https://guides.rubyonrails.org/v5.2/routing.html')

  namespace :admin do
    get 'users', to: "users#index"
    resources :students
    resources :sellers
  end


  namespace :animals do
    resources :cats
  end

  # scope module: :animals do
  #     resources :cats
  # end

  # this will remove the admin prefix from the url and is still use controller in admin folder
  # scope  module: :admin do
  #   resources :students
  # end

  # use prefix admin and use normal controller in controllers folder
  # scope :admin do
  #   resources :students
  # end

  # get "*path", to: redirect("/errors")

end

app/models/admin/student.rb
class Admin::Student < ApplicationRecord
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < ApplicationController
  before_action :set_admin_student, only: %i[ show edit update destroy ]

  # http://localhost:3000/admin/students


  # GET /admin/students or /admin/students.json
  def index
    @admin_students = Admin::Student.all
  end

  # GET /admin/students/1 or /admin/students/1.json
  def show
  end

  # GET /admin/students/new
  def new
    @admin_student = Admin::Student.new
  end

  # GET /admin/students/1/edit
  def edit
  end

  # POST /admin/students or /admin/students.json
  def create
    @admin_student = Admin::Student.new(admin_student_params)

    respond_to do |format|
      if @admin_student.save
        format.html { redirect_to admin_student_url(@admin_student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @admin_student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/students/1 or /admin/students/1.json
  def update
    respond_to do |format|
      if @admin_student.update(admin_student_params)
        format.html { redirect_to admin_student_url(@admin_student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/students/1 or /admin/students/1.json
  def destroy
    @admin_student.destroy

    respond_to do |format|
      format.html { redirect_to admin_students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_student
      @admin_student = Admin::Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_student_params
      params.require(:admin_student).permit(:name, :email)
    end
end

app/helpers/admin/students_helper.rb
module Admin::StudentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admin/students/_form.html.erb
<%= form_with(model: admin_student, local: true) do |form| %>
  <% if admin_student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_student.errors.count, "error") %> prohibited this admin_student from being saved:</h2>

      <ul>
      <% admin_student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/students/edit.html.erb
<h1>Editing Admin Student</h1>

<%= render 'form', admin_student: @admin_student %>

<%= link_to 'Show', @admin_student %> |
<%= link_to 'Back', admin_students_path %>

app/views/admin/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_students.each do |admin_student| %>
      <tr>
        <td><%= admin_student.name %></td>
        <td><%= admin_student.email %></td>
        <td><%= link_to 'Show', admin_student %></td>
        <td><%= link_to 'Edit', edit_admin_student_path(admin_student) %></td>
        <td><%= link_to 'Destroy', admin_student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Student', new_admin_student_path %>

app/views/admin/students/new.html.erb
<h1>New Admin Student</h1>

<%= render 'form', admin_student: @admin_student %>

<%= link_to 'Back', admin_students_path %>

app/views/admin/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_student.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin_student.email %>
</p>

<%= link_to 'Edit', edit_admin_student_path(@admin_student) %> |
<%= link_to 'Back', admin_students_path %>