config/routes.rb
Rails.application.routes.draw do

  # get 'products/index'
  # get 'products/show'

  get 'products', to: 'products#index', as: 'products'
# ^verb  ^URI          ^controller#action    ^ refer: products_path

  get 'products/:id', to: 'products#show',  as: 'product' , id: /\d+/
  # ^verb  ^URI          ^controller  ^action    ^ refer: product_path  ^constraint (for numeric values only)

  get 'about' => 'products#about'

  get 'blog', to: redirect('https://guides.rubyonrails.org/v5.2/routing.html')

  namespace :admin do
    get 'users', to: "users#index"
    resources :students
    resources :sellers
  end


  namespace :animals do
    resources :cats
  end

  # scope module: :animals do
  #     resources :cats
  # end

  # this will remove the admin prefix from the url and is still use controller in admin folder
  # scope  module: :admin do
  #   resources :students
  # end

  # use prefix admin and use normal controller in controllers folder
  # scope :admin do
  #   resources :students
  # end

  # get "*path", to: redirect("/errors")

end

app/models/admin/seller.rb
class Admin::Seller < ApplicationRecord
end

app/controllers/admin/sellers_controller.rb
class Admin::SellersController < ApplicationController
  before_action :set_admin_seller, only: %i[ show edit update destroy ]

  # http://localhost:3000/admin/sellers

  # GET /admin/sellers or /admin/sellers.json
  def index
    @admin_sellers = Admin::Seller.all
  end

  # GET /admin/sellers/1 or /admin/sellers/1.json
  def show
  end

  # GET /admin/sellers/new
  def new
    @admin_seller = Admin::Seller.new
  end

  # GET /admin/sellers/1/edit
  def edit
  end

  # POST /admin/sellers or /admin/sellers.json
  def create
    @admin_seller = Admin::Seller.new(admin_seller_params)

    respond_to do |format|
      if @admin_seller.save
        format.html { redirect_to admin_seller_url(@admin_seller), notice: "Seller was successfully created." }
        format.json { render :show, status: :created, location: @admin_seller }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/sellers/1 or /admin/sellers/1.json
  def update
    respond_to do |format|
      if @admin_seller.update(admin_seller_params)
        format.html { redirect_to admin_seller_url(@admin_seller), notice: "Seller was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_seller }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/sellers/1 or /admin/sellers/1.json
  def destroy
    @admin_seller.destroy

    respond_to do |format|
      format.html { redirect_to admin_sellers_url, notice: "Seller was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_seller
      @admin_seller = Admin::Seller.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_seller_params
      params.require(:admin_seller).permit(:name)
    end
end

app/helpers/admin/sellers_helper.rb
module Admin::SellersHelper
end

app/views/admin/sellers/_form.html.erb
<%= form_with(model: admin_seller, local: true) do |form| %>
  <% if admin_seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_seller.errors.count, "error") %> prohibited this admin_seller from being saved:</h2>

      <ul>
      <% admin_seller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/sellers/edit.html.erb
<h1>Editing Admin Seller</h1>

<%= render 'form', admin_seller: @admin_seller %>

<%= link_to 'Show', @admin_seller %> |
<%= link_to 'Back', admin_sellers_path %>

app/views/admin/sellers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Sellers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_sellers.each do |admin_seller| %>
      <tr>
        <td><%= admin_seller.name %></td>
        <td><%= link_to 'Show', admin_seller %></td>
        <td><%= link_to 'Edit', edit_admin_seller_path(admin_seller) %></td>
        <td><%= link_to 'Destroy', admin_seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Seller', new_admin_seller_path %>

app/views/admin/sellers/new.html.erb
<h1>New Admin Seller</h1>

<%= render 'form', admin_seller: @admin_seller %>

<%= link_to 'Back', admin_sellers_path %>

app/views/admin/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_seller.name %>
</p>

<%= link_to 'Edit', edit_admin_seller_path(@admin_seller) %> |
<%= link_to 'Back', admin_sellers_path %>