config/routes.rb
Rails.application.routes.draw do

  # get 'products/index'
  # get 'products/show'

  get 'products', to: 'products#index', as: 'products'
# ^verb  ^URI          ^controller#action    ^ refer: products_path

  get 'products/:id', to: 'products#show',  as: 'product' , id: /\d+/
  # ^verb  ^URI          ^controller  ^action    ^ refer: product_path  ^constraint (for numeric values only)

  get 'about' => 'products#about'

  get 'blog', to: redirect('https://guides.rubyonrails.org/v5.2/routing.html')

  namespace :admin do
    get 'users', to: "users#index"
    resources :students
    resources :sellers
  end


  namespace :animals do
    resources :cats
  end

  # scope module: :animals do
  #     resources :cats
  # end

  # this will remove the admin prefix from the url and is still use controller in admin folder
  # scope  module: :admin do
  #   resources :students
  # end

  # use prefix admin and use normal controller in controllers folder
  # scope :admin do
  #   resources :students
  # end

  # get "*path", to: redirect("/errors")

end

app/helpers/blog/blogs_helper.rb
module Blog::BlogsHelper
end

app/views/blog/blogs/_form.html.erb
<%= form_with(model: blog_blog, local: true) do |form| %>
  <% if blog_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_blog.errors.count, "error") %> prohibited this blog_blog from being saved:</h2>

      <ul>
      <% blog_blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blog/blogs/edit.html.erb
<h1>Editing Blog Blog</h1>

<%= render 'form', blog_blog: @blog_blog %>

<%= link_to 'Show', @blog_blog %> |
<%= link_to 'Back', blog_blogs_path %>

app/views/blog/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_blogs.each do |blog_blog| %>
      <tr>
        <td><%= blog_blog.name %></td>
        <td><%= link_to 'Show', blog_blog %></td>
        <td><%= link_to 'Edit', edit_blog_blog_path(blog_blog) %></td>
        <td><%= link_to 'Destroy', blog_blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog Blog', new_blog_blog_path %>

app/views/blog/blogs/new.html.erb
<h1>New Blog Blog</h1>

<%= render 'form', blog_blog: @blog_blog %>

<%= link_to 'Back', blog_blogs_path %>

app/views/blog/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blog_blog.name %>
</p>

<%= link_to 'Edit', edit_blog_blog_path(@blog_blog) %> |
<%= link_to 'Back', blog_blogs_path %>