config/routes.rb
Rails.application.routes.draw do

  # get 'products/index'
  # get 'products/show'

  get 'products', to: 'products#index', as: 'products'
# ^verb  ^URI          ^controller#action    ^ refer: products_path

  get 'products/:id', to: 'products#show',  as: 'product' , id: /\d+/
  # ^verb  ^URI          ^controller  ^action    ^ refer: product_path  ^constraint (for numeric values only)

  get 'about' => 'products#about'

  get 'blog', to: redirect('https://guides.rubyonrails.org/v5.2/routing.html')

  namespace :admin do
    get 'users', to: "users#index"
    resources :students
    resources :sellers
  end


  namespace :animals do
    resources :cats
  end

  # scope module: :animals do
  #     resources :cats
  # end

  # this will remove the admin prefix from the url and is still use controller in admin folder
  # scope  module: :admin do
  #   resources :students
  # end

  # use prefix admin and use normal controller in controllers folder
  # scope :admin do
  #   resources :students
  # end

  # get "*path", to: redirect("/errors")

end

app/models/animals.rb
module Animals
  def self.table_name_prefix
    'animals_'
  end
end

app/models/animals/cat.rb
class Animals::Cat < ApplicationRecord
end

app/controllers/animals/cats_controller.rb
class Animals::CatsController < ApplicationController
  before_action :set_animals_cat, only: %i[ show edit update destroy ]

  # GET /animals/cats or /animals/cats.json
  def index
    @animals_cats = Animals::Cat.all
  end

  # GET /animals/cats/1 or /animals/cats/1.json
  def show
  end

  # GET /animals/cats/new
  def new
    @animals_cat = Animals::Cat.new
  end

  # GET /animals/cats/1/edit
  def edit
  end

  # POST /animals/cats or /animals/cats.json
  def create
    @animals_cat = Animals::Cat.new(animals_cat_params)

    respond_to do |format|
      if @animals_cat.save
        format.html { redirect_to animals_cat_url(@animals_cat), notice: "Cat was successfully created." }
        format.json { render :show, status: :created, location: @animals_cat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animals_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/cats/1 or /animals/cats/1.json
  def update
    respond_to do |format|
      if @animals_cat.update(animals_cat_params)
        format.html { redirect_to animals_cat_url(@animals_cat), notice: "Cat was successfully updated." }
        format.json { render :show, status: :ok, location: @animals_cat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animals_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/cats/1 or /animals/cats/1.json
  def destroy
    @animals_cat.destroy

    respond_to do |format|
      format.html { redirect_to animals_cats_url, notice: "Cat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animals_cat
      @animals_cat = Animals::Cat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animals_cat_params
      params.require(:animals_cat).permit(:name, :age)
    end
end

app/helpers/animals/cats_helper.rb
module Animals::CatsHelper
end

app/views/animals/cats/_form.html.erb
<%= form_with(model: animals_cat, local: true) do |form| %>
  <% if animals_cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animals_cat.errors.count, "error") %> prohibited this animals_cat from being saved:</h2>

      <ul>
      <% animals_cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/cats/edit.html.erb
<h1>Editing Animals Cat</h1>

<%= render 'form', animals_cat: @animals_cat %>

<%= link_to 'Show', @animals_cat %> |
<%= link_to 'Back', animals_cats_path %>

app/views/animals/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals Cats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals_cats.each do |animals_cat| %>
      <tr>
        <td><%= animals_cat.name %></td>
        <td><%= animals_cat.age %></td>
        <td><%= link_to 'Show', animals_cat %></td>
        <td><%= link_to 'Edit', edit_animals_cat_path(animals_cat) %></td>
        <td><%= link_to 'Destroy', animals_cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animals Cat', new_animals_cat_path %>

app/views/animals/cats/new.html.erb
<h1>New Animals Cat</h1>

<%= render 'form', animals_cat: @animals_cat %>

<%= link_to 'Back', animals_cats_path %>

app/views/animals/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @animals_cat.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @animals_cat.age %>
</p>

<%= link_to 'Edit', edit_animals_cat_path(@animals_cat) %> |
<%= link_to 'Back', animals_cats_path %>